version: "3.9"
services:
  fise-app:
    restart: always
    env_file:
      - ./app/.env.local
    build: ./app
    stdin_open: true
    ports:
      - "3001:3001"
    depends_on:
      - fise-server
  fise-server:
    restart: always
    env_file:
      - ./server/.env.local
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
